version: '3.8'

services:
  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - mysql_directory:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  mysql_directory: {}
